services:
    hello-app-dev:
        build: .
        command: npm run dev # starts nodemon
        ports: 
            - 3000:3000
        volumes:
            - ./:/app
            - node_modules:/app/node_modules
        container_name: hello-app-dev

volumes:
    node_modules: